.PHONY: clean dockerfiles

dockerfiles: Dockerfile.base Dockerfile.jupyter

Dockerfile.base: _Dockerfile.header_base _Dockerfile.body _Dockerfile.footer_base
	cat $^ > $@

Dockerfile.jupyter: _Dockerfile.header_jupyter _Dockerfile.body _Dockerfile.footer_jupyter
	cat $^ > $@

clean:
	rm Dockerfile.*
