name: Latest Base
on:
  push:
    branches:
      - develop

jobs:
  actions:
    runs-on: ubuntu-18.04
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen Base
      run: docker build --tag islasgeci/base:latest .
    - name: Ejecuta objetivo principal del Makefile en Base
      run: docker run --volume ${PWD}:/workdir islasgeci/base:latest make
    - name: Docker log-in
      env:
        docker_username: ${{ secrets.docker_username }}
        docker_password: ${{ secrets.docker_password }}
      run: echo "${docker_password}" | docker login -u "${docker_username}" --password-stdin
    - name: Sube Base a Docker Hub
      run: docker push islasgeci/base:latest
