name: Check build
on: pull_request

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen Base
      run: docker build --tag islasgeci/base .
    - name: Corre las pruebas
      run: docker run --volume ${PWD}:/workdir islasgeci/base make tests
