name: Prueba imágenes Base y Jupyter
on: [push, pull_request]

jobs:
  actions:
    runs-on: ubuntu-18.04
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye Dockerfiles
      run: make --makefile=Makefile.build dockerfiles
    - name: Construye imagen Base
      run: docker build --tag islasgeci/base --file Dockerfile.base .
    - name: Construye imagen Jupyter
      run: docker build --tag islasgeci/jupyter --file Dockerfile.jupyter .
    - name: Ejecuta objetivo principal del Makefile en Base
      run: docker run --volume ${PWD}:/workdir islasgeci/base make
    - name: Ejecuta objetivo principal del Makefile en Jupyter
      run: docker run --volume ${PWD}:/workdir islasgeci/jupyter make
