name: Prueba imagen Base
on: [push, pull_request]

jobs:
  actions:
    runs-on: ubuntu-18.04
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen Base
      run: docker build --tag islasgeci/base .
    - name: Corre las pruebas
      run: docker run --volume ${PWD}:/workdir islasgeci/base make tests
